import { parse, postprocess, preprocess } from "micromark";
import type { Event, Token, TokenizeContext } from "micromark-util-types";
import { expect, it } from "vitest";

import { sapphireSyntax } from "../src/syntax.js";

it.for<{
	input: string;
	expected: [["enter" | "exit", Partial<Token>, Partial<TokenizeContext>], string][];
}>([
	{
		input: "[青空]<<あおぞら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<あおぞら>>"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<あおぞら>>"],
			[["enter", { type: "ruby" }, {}], "[青空]<<あおぞら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青空"],
			[["enter", { type: "data" }, {}], "青空"],
			[["exit", { type: "data" }, {}], "青空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青空"],
			[["exit", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["enter", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["exit", { type: "ruby" }, {}], "[青空]<<あおぞら>>"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<あおぞら>>"],
			[["exit", { type: "content" }, {}], "[青空]<<あおぞら>>"],
		],
	},
	{
		input: "[青|空]<<あお|ぞら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青|空]<<あお|ぞら>>"],
			[["enter", { type: "paragraph" }, {}], "[青|空]<<あお|ぞら>>"],
			[["enter", { type: "ruby" }, {}], "[青|空]<<あお|ぞら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青|空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青|空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "data" }, {}], "青"],
			[["exit", { type: "data" }, {}], "青"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "data" }, {}], "空"],
			[["exit", { type: "data" }, {}], "空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "空"],
			[["exit", { type: "rubyLabelContent" }, {}], "青|空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青|空]"],
			[["enter", { type: "rubyText" }, {}], "<<あお|ぞら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あお|ぞら"],
			[["enter", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "data" }, {}], "あお"],
			[["exit", { type: "data" }, {}], "あお"],
			[["exit", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyTextSegment" }, {}], "ぞら"],
			[["enter", { type: "data" }, {}], "ぞら"],
			[["exit", { type: "data" }, {}], "ぞら"],
			[["exit", { type: "rubyTextSegment" }, {}], "ぞら"],
			[["exit", { type: "rubyTextContent" }, {}], "あお|ぞら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あお|ぞら>>"],
			[["exit", { type: "ruby" }, {}], "[青|空]<<あお|ぞら>>"],
			[["exit", { type: "paragraph" }, {}], "[青|空]<<あお|ぞら>>"],
			[["exit", { type: "content" }, {}], "[青|空]<<あお|ぞら>>"],
		],
	},
	{
		input: "今日は[青|空]<<あお|ぞら>>です。",
		expected: [
			[["enter", { type: "content" }, {}], "今日は[青|空]<<あお|ぞら>>です。"],
			[["enter", { type: "paragraph" }, {}], "今日は[青|空]<<あお|ぞら>>です。"],
			[["enter", { type: "data" }, {}], "今日は"],
			[["exit", { type: "data" }, {}], "今日は"],
			[["enter", { type: "ruby" }, {}], "[青|空]<<あお|ぞら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青|空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青|空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "data" }, {}], "青"],
			[["exit", { type: "data" }, {}], "青"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "data" }, {}], "空"],
			[["exit", { type: "data" }, {}], "空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "空"],
			[["exit", { type: "rubyLabelContent" }, {}], "青|空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青|空]"],
			[["enter", { type: "rubyText" }, {}], "<<あお|ぞら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あお|ぞら"],
			[["enter", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "data" }, {}], "あお"],
			[["exit", { type: "data" }, {}], "あお"],
			[["exit", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyTextSegment" }, {}], "ぞら"],
			[["enter", { type: "data" }, {}], "ぞら"],
			[["exit", { type: "data" }, {}], "ぞら"],
			[["exit", { type: "rubyTextSegment" }, {}], "ぞら"],
			[["exit", { type: "rubyTextContent" }, {}], "あお|ぞら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あお|ぞら>>"],
			[["exit", { type: "ruby" }, {}], "[青|空]<<あお|ぞら>>"],
			[["enter", { type: "data" }, {}], "です。"],
			[["exit", { type: "data" }, {}], "です。"],
			[["exit", { type: "paragraph" }, {}], "今日は[青|空]<<あお|ぞら>>です。"],
			[["exit", { type: "content" }, {}], "今日は[青|空]<<あお|ぞら>>です。"],
		],
	},
	{
		input: "[**青空**]<<あおぞら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[**青空**]<<あおぞら>>"],
			[["enter", { type: "paragraph" }, {}], "[**青空**]<<あおぞら>>"],
			[["enter", { type: "ruby" }, {}], "[**青空**]<<あおぞら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[**青空**]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "**青空**"],
			[["enter", { type: "rubyLabelSegment" }, {}], "**青空**"],
			[["enter", { type: "strong" }, {}], "**青空**"],
			[["enter", { type: "strongSequence" }, {}], "**"],
			[["exit", { type: "strongSequence" }, {}], "**"],
			[["enter", { type: "strongText" }, {}], "青空"],
			[["enter", { type: "data" }, {}], "青空"],
			[["exit", { type: "data" }, {}], "青空"],
			[["exit", { type: "strongText" }, {}], "青空"],
			[["enter", { type: "strongSequence" }, {}], "**"],
			[["exit", { type: "strongSequence" }, {}], "**"],
			[["exit", { type: "strong" }, {}], "**青空**"],
			[["exit", { type: "rubyLabelSegment" }, {}], "**青空**"],
			[["exit", { type: "rubyLabelContent" }, {}], "**青空**"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[**青空**]"],
			[["enter", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["enter", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["exit", { type: "ruby" }, {}], "[**青空**]<<あおぞら>>"],
			[["exit", { type: "paragraph" }, {}], "[**青空**]<<あおぞら>>"],
			[["exit", { type: "content" }, {}], "[**青空**]<<あおぞら>>"],
		],
	},
	{
		input: "[青天|の|霹靂]<<せいてん||へきれき>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青天|の|霹靂]<<せいてん||へきれき>>"],
			[["enter", { type: "paragraph" }, {}], "[青天|の|霹靂]<<せいてん||へきれき>>"],
			[["enter", { type: "ruby" }, {}], "[青天|の|霹靂]<<せいてん||へきれき>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青天|の|霹靂]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青天|の|霹靂"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青天"],
			[["enter", { type: "data" }, {}], "青天"],
			[["exit", { type: "data" }, {}], "青天"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青天"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "の"],
			[["enter", { type: "data" }, {}], "の"],
			[["exit", { type: "data" }, {}], "の"],
			[["exit", { type: "rubyLabelSegment" }, {}], "の"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "霹靂"],
			[["enter", { type: "data" }, {}], "霹靂"],
			[["exit", { type: "data" }, {}], "霹靂"],
			[["exit", { type: "rubyLabelSegment" }, {}], "霹靂"],
			[["exit", { type: "rubyLabelContent" }, {}], "青天|の|霹靂"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青天|の|霹靂]"],
			[["enter", { type: "rubyText" }, {}], "<<せいてん||へきれき>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "せいてん||へきれき"],
			[["enter", { type: "rubyTextSegment" }, {}], "せいてん"],
			[["enter", { type: "data" }, {}], "せいてん"],
			[["exit", { type: "data" }, {}], "せいてん"],
			[["exit", { type: "rubyTextSegment" }, {}], "せいてん"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyTextSegment" }, {}], "へきれき"],
			[["enter", { type: "data" }, {}], "へきれき"],
			[["exit", { type: "data" }, {}], "へきれき"],
			[["exit", { type: "rubyTextSegment" }, {}], "へきれき"],
			[["exit", { type: "rubyTextContent" }, {}], "せいてん||へきれき"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<せいてん||へきれき>>"],
			[["exit", { type: "ruby" }, {}], "[青天|の|霹靂]<<せいてん||へきれき>>"],
			[["exit", { type: "paragraph" }, {}], "[青天|の|霹靂]<<せいてん||へきれき>>"],
			[["exit", { type: "content" }, {}], "[青天|の|霹靂]<<せいてん||へきれき>>"],
		],
	},
	{
		input: "[青空]<<あおぞら>",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<あおぞら>"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<あおぞら>"],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], "青空]<<あおぞら>"],
			[["exit", { type: "data" }, {}], "青空]<<あおぞら>"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<あおぞら>"],
			[["exit", { type: "content" }, {}], "[青空]<<あおぞら>"],
		],
	},
	{
		input: "[の|霹靂]<<|へきれき>>",
		expected: [
			[["enter", { type: "content" }, {}], "[の|霹靂]<<|へきれき>>"],
			[["enter", { type: "paragraph" }, {}], "[の|霹靂]<<|へきれき>>"],
			[["enter", { type: "ruby" }, {}], "[の|霹靂]<<|へきれき>>"],
			[["enter", { type: "rubyLabel" }, {}], "[の|霹靂]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "の|霹靂"],
			[["enter", { type: "rubyLabelSegment" }, {}], "の"],
			[["enter", { type: "data" }, {}], "の"],
			[["exit", { type: "data" }, {}], "の"],
			[["exit", { type: "rubyLabelSegment" }, {}], "の"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "霹靂"],
			[["enter", { type: "data" }, {}], "霹靂"],
			[["exit", { type: "data" }, {}], "霹靂"],
			[["exit", { type: "rubyLabelSegment" }, {}], "霹靂"],
			[["exit", { type: "rubyLabelContent" }, {}], "の|霹靂"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[の|霹靂]"],
			[["enter", { type: "rubyText" }, {}], "<<|へきれき>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "|へきれき"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyTextSegment" }, {}], "へきれき"],
			[["enter", { type: "data" }, {}], "へきれき"],
			[["exit", { type: "data" }, {}], "へきれき"],
			[["exit", { type: "rubyTextSegment" }, {}], "へきれき"],
			[["exit", { type: "rubyTextContent" }, {}], "|へきれき"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<|へきれき>>"],
			[["exit", { type: "ruby" }, {}], "[の|霹靂]<<|へきれき>>"],
			[["exit", { type: "paragraph" }, {}], "[の|霹靂]<<|へきれき>>"],
			[["exit", { type: "content" }, {}], "[の|霹靂]<<|へきれき>>"],
		],
	},
	{
		input: "[青天|の]<<せいてん|>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青天|の]<<せいてん|>>"],
			[["enter", { type: "paragraph" }, {}], "[青天|の]<<せいてん|>>"],
			[["enter", { type: "ruby" }, {}], "[青天|の]<<せいてん|>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青天|の]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青天|の"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青天"],
			[["enter", { type: "data" }, {}], "青天"],
			[["exit", { type: "data" }, {}], "青天"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青天"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "の"],
			[["enter", { type: "data" }, {}], "の"],
			[["exit", { type: "data" }, {}], "の"],
			[["exit", { type: "rubyLabelSegment" }, {}], "の"],
			[["exit", { type: "rubyLabelContent" }, {}], "青天|の"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青天|の]"],
			[["enter", { type: "rubyText" }, {}], "<<せいてん|>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "せいてん|"],
			[["enter", { type: "rubyTextSegment" }, {}], "せいてん"],
			[["enter", { type: "data" }, {}], "せいてん"],
			[["exit", { type: "data" }, {}], "せいてん"],
			[["exit", { type: "rubyTextSegment" }, {}], "せいてん"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyTextContent" }, {}], "せいてん|"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<せいてん|>>"],
			[["exit", { type: "ruby" }, {}], "[青天|の]<<せいてん|>>"],
			[["exit", { type: "paragraph" }, {}], "[青天|の]<<せいてん|>>"],
			[["exit", { type: "content" }, {}], "[青天|の]<<せいてん|>>"],
		],
	},
	{
		input: "[青天|の|霹靂]<<||>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青天|の|霹靂]<<||>>"],
			[["enter", { type: "paragraph" }, {}], "[青天|の|霹靂]<<||>>"],
			[["enter", { type: "ruby" }, {}], "[青天|の|霹靂]<<||>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青天|の|霹靂]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青天|の|霹靂"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青天"],
			[["enter", { type: "data" }, {}], "青天"],
			[["exit", { type: "data" }, {}], "青天"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青天"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "の"],
			[["enter", { type: "data" }, {}], "の"],
			[["exit", { type: "data" }, {}], "の"],
			[["exit", { type: "rubyLabelSegment" }, {}], "の"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "霹靂"],
			[["enter", { type: "data" }, {}], "霹靂"],
			[["exit", { type: "data" }, {}], "霹靂"],
			[["exit", { type: "rubyLabelSegment" }, {}], "霹靂"],
			[["exit", { type: "rubyLabelContent" }, {}], "青天|の|霹靂"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青天|の|霹靂]"],
			[["enter", { type: "rubyText" }, {}], "<<||>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "||"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyTextContent" }, {}], "||"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<||>>"],
			[["exit", { type: "ruby" }, {}], "[青天|の|霹靂]<<||>>"],
			[["exit", { type: "paragraph" }, {}], "[青天|の|霹靂]<<||>>"],
			[["exit", { type: "content" }, {}], "[青天|の|霹靂]<<||>>"],
		],
	},
	{
		input: "[青空]<<>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<>>"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<>>"],
			[["enter", { type: "ruby" }, {}], "[青空]<<>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青空"],
			[["enter", { type: "data" }, {}], "青空"],
			[["exit", { type: "data" }, {}], "青空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青空"],
			[["exit", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyText" }, {}], "<<>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<>>"],
			[["exit", { type: "ruby" }, {}], "[青空]<<>>"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<>>"],
			[["exit", { type: "content" }, {}], "[青空]<<>>"],
		],
	},
	{
		input: "[青|い|空|だ]<<あお||そら|>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青|い|空|だ]<<あお||そら|>>"],
			[["enter", { type: "paragraph" }, {}], "[青|い|空|だ]<<あお||そら|>>"],
			[["enter", { type: "ruby" }, {}], "[青|い|空|だ]<<あお||そら|>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青|い|空|だ]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青|い|空|だ"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "data" }, {}], "青"],
			[["exit", { type: "data" }, {}], "青"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "い"],
			[["enter", { type: "data" }, {}], "い"],
			[["exit", { type: "data" }, {}], "い"],
			[["exit", { type: "rubyLabelSegment" }, {}], "い"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "data" }, {}], "空"],
			[["exit", { type: "data" }, {}], "空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "だ"],
			[["enter", { type: "data" }, {}], "だ"],
			[["exit", { type: "data" }, {}], "だ"],
			[["exit", { type: "rubyLabelSegment" }, {}], "だ"],
			[["exit", { type: "rubyLabelContent" }, {}], "青|い|空|だ"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青|い|空|だ]"],
			[["enter", { type: "rubyText" }, {}], "<<あお||そら|>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あお||そら|"],
			[["enter", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "data" }, {}], "あお"],
			[["exit", { type: "data" }, {}], "あお"],
			[["exit", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyTextSegment" }, {}], "そら"],
			[["enter", { type: "data" }, {}], "そら"],
			[["exit", { type: "data" }, {}], "そら"],
			[["exit", { type: "rubyTextSegment" }, {}], "そら"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyTextContent" }, {}], "あお||そら|"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あお||そら|>>"],
			[["exit", { type: "ruby" }, {}], "[青|い|空|だ]<<あお||そら|>>"],
			[["exit", { type: "paragraph" }, {}], "[青|い|空|だ]<<あお||そら|>>"],
			[["exit", { type: "content" }, {}], "[青|い|空|だ]<<あお||そら|>>"],
		],
	},
	{
		input: "[青|い|空|だ]<<あお|||>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青|い|空|だ]<<あお|||>>"],
			[["enter", { type: "paragraph" }, {}], "[青|い|空|だ]<<あお|||>>"],
			[["enter", { type: "ruby" }, {}], "[青|い|空|だ]<<あお|||>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青|い|空|だ]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青|い|空|だ"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "data" }, {}], "青"],
			[["exit", { type: "data" }, {}], "青"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "い"],
			[["enter", { type: "data" }, {}], "い"],
			[["exit", { type: "data" }, {}], "い"],
			[["exit", { type: "rubyLabelSegment" }, {}], "い"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "data" }, {}], "空"],
			[["exit", { type: "data" }, {}], "空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "だ"],
			[["enter", { type: "data" }, {}], "だ"],
			[["exit", { type: "data" }, {}], "だ"],
			[["exit", { type: "rubyLabelSegment" }, {}], "だ"],
			[["exit", { type: "rubyLabelContent" }, {}], "青|い|空|だ"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青|い|空|だ]"],
			[["enter", { type: "rubyText" }, {}], "<<あお|||>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あお|||"],
			[["enter", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "data" }, {}], "あお"],
			[["exit", { type: "data" }, {}], "あお"],
			[["exit", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyTextContent" }, {}], "あお|||"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あお|||>>"],
			[["exit", { type: "ruby" }, {}], "[青|い|空|だ]<<あお|||>>"],
			[["exit", { type: "paragraph" }, {}], "[青|い|空|だ]<<あお|||>>"],
			[["exit", { type: "content" }, {}], "[青|い|空|だ]<<あお|||>>"],
		],
	},
	{
		input: "[青|い|空|だ]<<|||だ>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青|い|空|だ]<<|||だ>>"],
			[["enter", { type: "paragraph" }, {}], "[青|い|空|だ]<<|||だ>>"],
			[["enter", { type: "ruby" }, {}], "[青|い|空|だ]<<|||だ>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青|い|空|だ]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青|い|空|だ"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "data" }, {}], "青"],
			[["exit", { type: "data" }, {}], "青"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "い"],
			[["enter", { type: "data" }, {}], "い"],
			[["exit", { type: "data" }, {}], "い"],
			[["exit", { type: "rubyLabelSegment" }, {}], "い"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "data" }, {}], "空"],
			[["exit", { type: "data" }, {}], "空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "だ"],
			[["enter", { type: "data" }, {}], "だ"],
			[["exit", { type: "data" }, {}], "だ"],
			[["exit", { type: "rubyLabelSegment" }, {}], "だ"],
			[["exit", { type: "rubyLabelContent" }, {}], "青|い|空|だ"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青|い|空|だ]"],
			[["enter", { type: "rubyText" }, {}], "<<|||だ>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "|||だ"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyTextSegment" }, {}], "だ"],
			[["enter", { type: "data" }, {}], "だ"],
			[["exit", { type: "data" }, {}], "だ"],
			[["exit", { type: "rubyTextSegment" }, {}], "だ"],
			[["exit", { type: "rubyTextContent" }, {}], "|||だ"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<|||だ>>"],
			[["exit", { type: "ruby" }, {}], "[青|い|空|だ]<<|||だ>>"],
			[["exit", { type: "paragraph" }, {}], "[青|い|空|だ]<<|||だ>>"],
			[["exit", { type: "content" }, {}], "[青|い|空|だ]<<|||だ>>"],
		],
	},
	{
		input: "[青|い|空]<<|い|>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青|い|空]<<|い|>>"],
			[["enter", { type: "paragraph" }, {}], "[青|い|空]<<|い|>>"],
			[["enter", { type: "ruby" }, {}], "[青|い|空]<<|い|>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青|い|空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青|い|空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "data" }, {}], "青"],
			[["exit", { type: "data" }, {}], "青"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "い"],
			[["enter", { type: "data" }, {}], "い"],
			[["exit", { type: "data" }, {}], "い"],
			[["exit", { type: "rubyLabelSegment" }, {}], "い"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "data" }, {}], "空"],
			[["exit", { type: "data" }, {}], "空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "空"],
			[["exit", { type: "rubyLabelContent" }, {}], "青|い|空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青|い|空]"],
			[["enter", { type: "rubyText" }, {}], "<<|い|>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "|い|"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyTextSegment" }, {}], "い"],
			[["enter", { type: "data" }, {}], "い"],
			[["exit", { type: "data" }, {}], "い"],
			[["exit", { type: "rubyTextSegment" }, {}], "い"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyTextContent" }, {}], "|い|"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<|い|>>"],
			[["exit", { type: "ruby" }, {}], "[青|い|空]<<|い|>>"],
			[["exit", { type: "paragraph" }, {}], "[青|い|空]<<|い|>>"],
			[["exit", { type: "content" }, {}], "[青|い|空]<<|い|>>"],
		],
	},
	{
		input: "[青|い|空|だ]<<あお||そら|だ>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青|い|空|だ]<<あお||そら|だ>>"],
			[["enter", { type: "paragraph" }, {}], "[青|い|空|だ]<<あお||そら|だ>>"],
			[["enter", { type: "ruby" }, {}], "[青|い|空|だ]<<あお||そら|だ>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青|い|空|だ]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青|い|空|だ"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "data" }, {}], "青"],
			[["exit", { type: "data" }, {}], "青"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "い"],
			[["enter", { type: "data" }, {}], "い"],
			[["exit", { type: "data" }, {}], "い"],
			[["exit", { type: "rubyLabelSegment" }, {}], "い"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "data" }, {}], "空"],
			[["exit", { type: "data" }, {}], "空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "だ"],
			[["enter", { type: "data" }, {}], "だ"],
			[["exit", { type: "data" }, {}], "だ"],
			[["exit", { type: "rubyLabelSegment" }, {}], "だ"],
			[["exit", { type: "rubyLabelContent" }, {}], "青|い|空|だ"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青|い|空|だ]"],
			[["enter", { type: "rubyText" }, {}], "<<あお||そら|だ>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あお||そら|だ"],
			[["enter", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "data" }, {}], "あお"],
			[["exit", { type: "data" }, {}], "あお"],
			[["exit", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyTextSegment" }, {}], "そら"],
			[["enter", { type: "data" }, {}], "そら"],
			[["exit", { type: "data" }, {}], "そら"],
			[["exit", { type: "rubyTextSegment" }, {}], "そら"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyTextSegment" }, {}], "だ"],
			[["enter", { type: "data" }, {}], "だ"],
			[["exit", { type: "data" }, {}], "だ"],
			[["exit", { type: "rubyTextSegment" }, {}], "だ"],
			[["exit", { type: "rubyTextContent" }, {}], "あお||そら|だ"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あお||そら|だ>>"],
			[["exit", { type: "ruby" }, {}], "[青|い|空|だ]<<あお||そら|だ>>"],
			[["exit", { type: "paragraph" }, {}], "[青|い|空|だ]<<あお||そら|だ>>"],
			[["exit", { type: "content" }, {}], "[青|い|空|だ]<<あお||そら|だ>>"],
		],
	},
	{
		input: "[青|空]<<|>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青|空]<<|>>"],
			[["enter", { type: "paragraph" }, {}], "[青|空]<<|>>"],
			[["enter", { type: "ruby" }, {}], "[青|空]<<|>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青|空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青|空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "data" }, {}], "青"],
			[["exit", { type: "data" }, {}], "青"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "data" }, {}], "空"],
			[["exit", { type: "data" }, {}], "空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "空"],
			[["exit", { type: "rubyLabelContent" }, {}], "青|空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青|空]"],
			[["enter", { type: "rubyText" }, {}], "<<|>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "|"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyTextContent" }, {}], "|"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<|>>"],
			[["exit", { type: "ruby" }, {}], "[青|空]<<|>>"],
			[["exit", { type: "paragraph" }, {}], "[青|空]<<|>>"],
			[["exit", { type: "content" }, {}], "[青|空]<<|>>"],
		],
	},
	{
		input: "[*青空*]<<あおぞら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[*青空*]<<あおぞら>>"],
			[["enter", { type: "paragraph" }, {}], "[*青空*]<<あおぞら>>"],
			[["enter", { type: "ruby" }, {}], "[*青空*]<<あおぞら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[*青空*]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "*青空*"],
			[["enter", { type: "rubyLabelSegment" }, {}], "*青空*"],
			[["enter", { type: "emphasis" }, {}], "*青空*"],
			[["enter", { type: "emphasisSequence" }, {}], "*"],
			[["exit", { type: "emphasisSequence" }, {}], "*"],
			[["enter", { type: "emphasisText" }, {}], "青空"],
			[["enter", { type: "data" }, {}], "青空"],
			[["exit", { type: "data" }, {}], "青空"],
			[["exit", { type: "emphasisText" }, {}], "青空"],
			[["enter", { type: "emphasisSequence" }, {}], "*"],
			[["exit", { type: "emphasisSequence" }, {}], "*"],
			[["exit", { type: "emphasis" }, {}], "*青空*"],
			[["exit", { type: "rubyLabelSegment" }, {}], "*青空*"],
			[["exit", { type: "rubyLabelContent" }, {}], "*青空*"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[*青空*]"],
			[["enter", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["enter", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["exit", { type: "ruby" }, {}], "[*青空*]<<あおぞら>>"],
			[["exit", { type: "paragraph" }, {}], "[*青空*]<<あおぞら>>"],
			[["exit", { type: "content" }, {}], "[*青空*]<<あおぞら>>"],
		],
	},
	{
		input: "[`青空`]<<あおぞら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[`青空`]<<あおぞら>>"],
			[["enter", { type: "paragraph" }, {}], "[`青空`]<<あおぞら>>"],
			[["enter", { type: "ruby" }, {}], "[`青空`]<<あおぞら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[`青空`]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "`青空`"],
			[["enter", { type: "rubyLabelSegment" }, {}], "`青空`"],
			[["enter", { type: "codeText" }, {}], "`青空`"],
			[["enter", { type: "codeTextSequence" }, {}], "`"],
			[["exit", { type: "codeTextSequence" }, {}], "`"],
			[["enter", { type: "codeTextData" }, {}], "青空"],
			[["exit", { type: "codeTextData" }, {}], "青空"],
			[["enter", { type: "codeTextSequence" }, {}], "`"],
			[["exit", { type: "codeTextSequence" }, {}], "`"],
			[["exit", { type: "codeText" }, {}], "`青空`"],
			[["exit", { type: "rubyLabelSegment" }, {}], "`青空`"],
			[["exit", { type: "rubyLabelContent" }, {}], "`青空`"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[`青空`]"],
			[["enter", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["enter", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["exit", { type: "ruby" }, {}], "[`青空`]<<あおぞら>>"],
			[["exit", { type: "paragraph" }, {}], "[`青空`]<<あおぞら>>"],
			[["exit", { type: "content" }, {}], "[`青空`]<<あおぞら>>"],
		],
	},
	{
		input: "[青**空**]<<あおぞら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青**空**]<<あおぞら>>"],
			[["enter", { type: "paragraph" }, {}], "[青**空**]<<あおぞら>>"],
			[["enter", { type: "ruby" }, {}], "[青**空**]<<あおぞら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青**空**]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青**空**"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青**空**"],
			[["enter", { type: "data" }, {}], "青"],
			[["exit", { type: "data" }, {}], "青"],
			[["enter", { type: "strong" }, {}], "**空**"],
			[["enter", { type: "strongSequence" }, {}], "**"],
			[["exit", { type: "strongSequence" }, {}], "**"],
			[["enter", { type: "strongText" }, {}], "空"],
			[["enter", { type: "data" }, {}], "空"],
			[["exit", { type: "data" }, {}], "空"],
			[["exit", { type: "strongText" }, {}], "空"],
			[["enter", { type: "strongSequence" }, {}], "**"],
			[["exit", { type: "strongSequence" }, {}], "**"],
			[["exit", { type: "strong" }, {}], "**空**"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青**空**"],
			[["exit", { type: "rubyLabelContent" }, {}], "青**空**"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青**空**]"],
			[["enter", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["enter", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["exit", { type: "ruby" }, {}], "[青**空**]<<あおぞら>>"],
			[["exit", { type: "paragraph" }, {}], "[青**空**]<<あおぞら>>"],
			[["exit", { type: "content" }, {}], "[青**空**]<<あおぞら>>"],
		],
	},
	{
		input: "[\\*青空\\*]<<あおぞら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[\\*青空\\*]<<あおぞら>>"],
			[["enter", { type: "paragraph" }, {}], "[\\*青空\\*]<<あおぞら>>"],
			[["enter", { type: "ruby" }, {}], "[\\*青空\\*]<<あおぞら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[\\*青空\\*]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "\\*青空\\*"],
			[["enter", { type: "rubyLabelSegment" }, {}], "\\*青空\\*"],
			[["enter", { type: "characterEscape" }, {}], "\\*"],
			[["enter", { type: "escapeMarker" }, {}], "\\"],
			[["exit", { type: "escapeMarker" }, {}], "\\"],
			[["enter", { type: "characterEscapeValue" }, {}], "*"],
			[["exit", { type: "characterEscapeValue" }, {}], "*"],
			[["exit", { type: "characterEscape" }, {}], "\\*"],
			[["enter", { type: "data" }, {}], "青空"],
			[["exit", { type: "data" }, {}], "青空"],
			[["enter", { type: "characterEscape" }, {}], "\\*"],
			[["enter", { type: "escapeMarker" }, {}], "\\"],
			[["exit", { type: "escapeMarker" }, {}], "\\"],
			[["enter", { type: "characterEscapeValue" }, {}], "*"],
			[["exit", { type: "characterEscapeValue" }, {}], "*"],
			[["exit", { type: "characterEscape" }, {}], "\\*"],
			[["exit", { type: "rubyLabelSegment" }, {}], "\\*青空\\*"],
			[["exit", { type: "rubyLabelContent" }, {}], "\\*青空\\*"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[\\*青空\\*]"],
			[["enter", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["enter", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["exit", { type: "ruby" }, {}], "[\\*青空\\*]<<あおぞら>>"],
			[["exit", { type: "paragraph" }, {}], "[\\*青空\\*]<<あおぞら>>"],
			[["exit", { type: "content" }, {}], "[\\*青空\\*]<<あおぞら>>"],
		],
	},
	{
		input: "[**青**|*空*]<<あお|ぞら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[**青**|*空*]<<あお|ぞら>>"],
			[["enter", { type: "paragraph" }, {}], "[**青**|*空*]<<あお|ぞら>>"],
			[["enter", { type: "ruby" }, {}], "[**青**|*空*]<<あお|ぞら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[**青**|*空*]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "**青**|*空*"],
			[["enter", { type: "rubyLabelSegment" }, {}], "**青**"],
			[["enter", { type: "strong" }, {}], "**青**"],
			[["enter", { type: "strongSequence" }, {}], "**"],
			[["exit", { type: "strongSequence" }, {}], "**"],
			[["enter", { type: "strongText" }, {}], "青"],
			[["enter", { type: "data" }, {}], "青"],
			[["exit", { type: "data" }, {}], "青"],
			[["exit", { type: "strongText" }, {}], "青"],
			[["enter", { type: "strongSequence" }, {}], "**"],
			[["exit", { type: "strongSequence" }, {}], "**"],
			[["exit", { type: "strong" }, {}], "**青**"],
			[["exit", { type: "rubyLabelSegment" }, {}], "**青**"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyLabelSegment" }, {}], "*空*"],
			[["enter", { type: "emphasis" }, {}], "*空*"],
			[["enter", { type: "emphasisSequence" }, {}], "*"],
			[["exit", { type: "emphasisSequence" }, {}], "*"],
			[["enter", { type: "emphasisText" }, {}], "空"],
			[["enter", { type: "data" }, {}], "空"],
			[["exit", { type: "data" }, {}], "空"],
			[["exit", { type: "emphasisText" }, {}], "空"],
			[["enter", { type: "emphasisSequence" }, {}], "*"],
			[["exit", { type: "emphasisSequence" }, {}], "*"],
			[["exit", { type: "emphasis" }, {}], "*空*"],
			[["exit", { type: "rubyLabelSegment" }, {}], "*空*"],
			[["exit", { type: "rubyLabelContent" }, {}], "**青**|*空*"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[**青**|*空*]"],
			[["enter", { type: "rubyText" }, {}], "<<あお|ぞら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あお|ぞら"],
			[["enter", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "data" }, {}], "あお"],
			[["exit", { type: "data" }, {}], "あお"],
			[["exit", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "rubyDivider" }, {}], "|"],
			[["exit", { type: "rubyDivider" }, {}], "|"],
			[["enter", { type: "rubyTextSegment" }, {}], "ぞら"],
			[["enter", { type: "data" }, {}], "ぞら"],
			[["exit", { type: "data" }, {}], "ぞら"],
			[["exit", { type: "rubyTextSegment" }, {}], "ぞら"],
			[["exit", { type: "rubyTextContent" }, {}], "あお|ぞら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あお|ぞら>>"],
			[["exit", { type: "ruby" }, {}], "[**青**|*空*]<<あお|ぞら>>"],
			[["exit", { type: "paragraph" }, {}], "[**青**|*空*]<<あお|ぞら>>"],
			[["exit", { type: "content" }, {}], "[**青**|*空*]<<あお|ぞら>>"],
		],
	},
	{
		input: "[青空]<<**あおぞら**>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<**あおぞら**>>"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<**あおぞら**>>"],
			[["enter", { type: "ruby" }, {}], "[青空]<<**あおぞら**>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青空"],
			[["enter", { type: "data" }, {}], "青空"],
			[["exit", { type: "data" }, {}], "青空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青空"],
			[["exit", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyText" }, {}], "<<**あおぞら**>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "**あおぞら**"],
			[["enter", { type: "rubyTextSegment" }, {}], "**あおぞら**"],
			[["enter", { type: "data" }, {}], "**あおぞら**"],
			[["exit", { type: "data" }, {}], "**あおぞら**"],
			[["exit", { type: "rubyTextSegment" }, {}], "**あおぞら**"],
			[["exit", { type: "rubyTextContent" }, {}], "**あおぞら**"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<**あおぞら**>>"],
			[["exit", { type: "ruby" }, {}], "[青空]<<**あおぞら**>>"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<**あおぞら**>>"],
			[["exit", { type: "content" }, {}], "[青空]<<**あおぞら**>>"],
		],
	},
	{
		input: "[青空]<<`あおぞら`>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<`あおぞら`>>"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<`あおぞら`>>"],
			[["enter", { type: "ruby" }, {}], "[青空]<<`あおぞら`>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青空"],
			[["enter", { type: "data" }, {}], "青空"],
			[["exit", { type: "data" }, {}], "青空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青空"],
			[["exit", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyText" }, {}], "<<`あおぞら`>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "`あおぞら`"],
			[["enter", { type: "rubyTextSegment" }, {}], "`あおぞら`"],
			[["enter", { type: "data" }, {}], "`あおぞら`"],
			[["exit", { type: "data" }, {}], "`あおぞら`"],
			[["exit", { type: "rubyTextSegment" }, {}], "`あおぞら`"],
			[["exit", { type: "rubyTextContent" }, {}], "`あおぞら`"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<`あおぞら`>>"],
			[["exit", { type: "ruby" }, {}], "[青空]<<`あおぞら`>>"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<`あおぞら`>>"],
			[["exit", { type: "content" }, {}], "[青空]<<`あおぞら`>>"],
		],
	},
	{
		input: "[青空]<< あおぞら >>",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<< あおぞら >>"],
			[["enter", { type: "paragraph" }, {}], "[青空]<< あおぞら >>"],
			[["enter", { type: "ruby" }, {}], "[青空]<< あおぞら >>"],
			[["enter", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青空"],
			[["enter", { type: "data" }, {}], "青空"],
			[["exit", { type: "data" }, {}], "青空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青空"],
			[["exit", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyText" }, {}], "<< あおぞら >>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], " あおぞら "],
			[["enter", { type: "rubyTextSegment" }, {}], " あおぞら "],
			[["enter", { type: "data" }, {}], " あおぞら "],
			[["exit", { type: "data" }, {}], " あおぞら "],
			[["exit", { type: "rubyTextSegment" }, {}], " あおぞら "],
			[["exit", { type: "rubyTextContent" }, {}], " あおぞら "],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<< あおぞら >>"],
			[["exit", { type: "ruby" }, {}], "[青空]<< あおぞら >>"],
			[["exit", { type: "paragraph" }, {}], "[青空]<< あおぞら >>"],
			[["exit", { type: "content" }, {}], "[青空]<< あおぞら >>"],
		],
	},
	{
		input: "[青空]<<あお ぞら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<あお ぞら>>"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<あお ぞら>>"],
			[["enter", { type: "ruby" }, {}], "[青空]<<あお ぞら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青空"],
			[["enter", { type: "data" }, {}], "青空"],
			[["exit", { type: "data" }, {}], "青空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青空"],
			[["exit", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyText" }, {}], "<<あお ぞら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あお ぞら"],
			[["enter", { type: "rubyTextSegment" }, {}], "あお ぞら"],
			[["enter", { type: "data" }, {}], "あお ぞら"],
			[["exit", { type: "data" }, {}], "あお ぞら"],
			[["exit", { type: "rubyTextSegment" }, {}], "あお ぞら"],
			[["exit", { type: "rubyTextContent" }, {}], "あお ぞら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あお ぞら>>"],
			[["exit", { type: "ruby" }, {}], "[青空]<<あお ぞら>>"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<あお ぞら>>"],
			[["exit", { type: "content" }, {}], "[青空]<<あお ぞら>>"],
		],
	},
	{
		input: "[青]<<あお>>[空]<<そら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青]<<あお>>[空]<<そら>>"],
			[["enter", { type: "paragraph" }, {}], "[青]<<あお>>[空]<<そら>>"],
			[["enter", { type: "ruby" }, {}], "[青]<<あお>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "data" }, {}], "青"],
			[["exit", { type: "data" }, {}], "青"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青"],
			[["exit", { type: "rubyLabelContent" }, {}], "青"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青]"],
			[["enter", { type: "rubyText" }, {}], "<<あお>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あお"],
			[["enter", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "data" }, {}], "あお"],
			[["exit", { type: "data" }, {}], "あお"],
			[["exit", { type: "rubyTextSegment" }, {}], "あお"],
			[["exit", { type: "rubyTextContent" }, {}], "あお"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あお>>"],
			[["exit", { type: "ruby" }, {}], "[青]<<あお>>"],
			[["enter", { type: "ruby" }, {}], "[空]<<そら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "data" }, {}], "空"],
			[["exit", { type: "data" }, {}], "空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "空"],
			[["exit", { type: "rubyLabelContent" }, {}], "空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[空]"],
			[["enter", { type: "rubyText" }, {}], "<<そら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "そら"],
			[["enter", { type: "rubyTextSegment" }, {}], "そら"],
			[["enter", { type: "data" }, {}], "そら"],
			[["exit", { type: "data" }, {}], "そら"],
			[["exit", { type: "rubyTextSegment" }, {}], "そら"],
			[["exit", { type: "rubyTextContent" }, {}], "そら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<そら>>"],
			[["exit", { type: "ruby" }, {}], "[空]<<そら>>"],
			[["exit", { type: "paragraph" }, {}], "[青]<<あお>>[空]<<そら>>"],
			[["exit", { type: "content" }, {}], "[青]<<あお>>[空]<<そら>>"],
		],
	},
	{
		input: "[青]<<あお>>と[空]<<そら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青]<<あお>>と[空]<<そら>>"],
			[["enter", { type: "paragraph" }, {}], "[青]<<あお>>と[空]<<そら>>"],
			[["enter", { type: "ruby" }, {}], "[青]<<あお>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青"],
			[["enter", { type: "data" }, {}], "青"],
			[["exit", { type: "data" }, {}], "青"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青"],
			[["exit", { type: "rubyLabelContent" }, {}], "青"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青]"],
			[["enter", { type: "rubyText" }, {}], "<<あお>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あお"],
			[["enter", { type: "rubyTextSegment" }, {}], "あお"],
			[["enter", { type: "data" }, {}], "あお"],
			[["exit", { type: "data" }, {}], "あお"],
			[["exit", { type: "rubyTextSegment" }, {}], "あお"],
			[["exit", { type: "rubyTextContent" }, {}], "あお"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あお>>"],
			[["exit", { type: "ruby" }, {}], "[青]<<あお>>"],
			[["enter", { type: "data" }, {}], "と"],
			[["exit", { type: "data" }, {}], "と"],
			[["enter", { type: "ruby" }, {}], "[空]<<そら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "空"],
			[["enter", { type: "data" }, {}], "空"],
			[["exit", { type: "data" }, {}], "空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "空"],
			[["exit", { type: "rubyLabelContent" }, {}], "空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[空]"],
			[["enter", { type: "rubyText" }, {}], "<<そら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "そら"],
			[["enter", { type: "rubyTextSegment" }, {}], "そら"],
			[["enter", { type: "data" }, {}], "そら"],
			[["exit", { type: "data" }, {}], "そら"],
			[["exit", { type: "rubyTextSegment" }, {}], "そら"],
			[["exit", { type: "rubyTextContent" }, {}], "そら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<そら>>"],
			[["exit", { type: "ruby" }, {}], "[空]<<そら>>"],
			[["exit", { type: "paragraph" }, {}], "[青]<<あお>>と[空]<<そら>>"],
			[["exit", { type: "content" }, {}], "[青]<<あお>>と[空]<<そら>>"],
		],
	},
	{
		input: "[青空]<<あおぞら>>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<あおぞら>>>"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<あおぞら>>>"],
			[["enter", { type: "ruby" }, {}], "[青空]<<あおぞら>>"],
			[["enter", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyLabelMarker" }, {}], "["],
			[["exit", { type: "rubyLabelMarker" }, {}], "["],
			[["enter", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelSegment" }, {}], "青空"],
			[["enter", { type: "data" }, {}], "青空"],
			[["exit", { type: "data" }, {}], "青空"],
			[["exit", { type: "rubyLabelSegment" }, {}], "青空"],
			[["exit", { type: "rubyLabelContent" }, {}], "青空"],
			[["enter", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabelMarker" }, {}], "]"],
			[["exit", { type: "rubyLabel" }, {}], "[青空]"],
			[["enter", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["enter", { type: "rubyTextMarker" }, {}], "<<"],
			[["exit", { type: "rubyTextMarker" }, {}], "<<"],
			[["enter", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["enter", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "data" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextSegment" }, {}], "あおぞら"],
			[["exit", { type: "rubyTextContent" }, {}], "あおぞら"],
			[["enter", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyTextMarker" }, {}], ">>"],
			[["exit", { type: "rubyText" }, {}], "<<あおぞら>>"],
			[["exit", { type: "ruby" }, {}], "[青空]<<あおぞら>>"],
			[["enter", { type: "data" }, {}], ">"],
			[["exit", { type: "data" }, {}], ">"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<あおぞら>>>"],
			[["exit", { type: "content" }, {}], "[青空]<<あおぞら>>>"],
		],
	},
	{
		input: "[青空",
		expected: [
			[["enter", { type: "content" }, {}], "[青空"],
			[["enter", { type: "paragraph" }, {}], "[青空"],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], "青空"],
			[["exit", { type: "data" }, {}], "青空"],
			[["exit", { type: "paragraph" }, {}], "[青空"],
			[["exit", { type: "content" }, {}], "[青空"],
		],
	},
	{
		input: "[青空]",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]"],
			[["enter", { type: "paragraph" }, {}], "[青空]"],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], "青空]"],
			[["exit", { type: "data" }, {}], "青空]"],
			[["exit", { type: "paragraph" }, {}], "[青空]"],
			[["exit", { type: "content" }, {}], "[青空]"],
		],
	},
	{
		input: "[青空]<",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<"],
			[["enter", { type: "paragraph" }, {}], "[青空]<"],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], "青空]<"],
			[["exit", { type: "data" }, {}], "青空]<"],
			[["exit", { type: "paragraph" }, {}], "[青空]<"],
			[["exit", { type: "content" }, {}], "[青空]<"],
		],
	},
	{
		input: "[青空]<<",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<"],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], "青空]<<"],
			[["exit", { type: "data" }, {}], "青空]<<"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<"],
			[["exit", { type: "content" }, {}], "[青空]<<"],
		],
	},
	{
		input: "[青空]<<あおぞら",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<あおぞら"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<あおぞら"],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], "青空]<<あおぞら"],
			[["exit", { type: "data" }, {}], "青空]<<あおぞら"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<あおぞら"],
			[["exit", { type: "content" }, {}], "[青空]<<あおぞら"],
		],
	},
	{
		input: "[青空]<<|",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<|"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<|"],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], "青空]<<|"],
			[["exit", { type: "data" }, {}], "青空]<<|"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<|"],
			[["exit", { type: "content" }, {}], "[青空]<<|"],
		],
	},
	{
		input: "[青空]<<あお|",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<あお|"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<あお|"],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], "青空]<<あお|"],
			[["exit", { type: "data" }, {}], "青空]<<あお|"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<あお|"],
			[["exit", { type: "content" }, {}], "[青空]<<あお|"],
		],
	},
	{
		input: "[青空]<<>",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<>"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<>"],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], "青空]<<>"],
			[["exit", { type: "data" }, {}], "青空]<<>"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<>"],
			[["exit", { type: "content" }, {}], "[青空]<<>"],
		],
	},
	{
		input: "[青空]<あおぞら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<あおぞら>>"],
			[["enter", { type: "paragraph" }, {}], "[青空]<あおぞら>>"],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], "青空]<あおぞら>>"],
			[["exit", { type: "data" }, {}], "青空]<あおぞら>>"],
			[["exit", { type: "paragraph" }, {}], "[青空]<あおぞら>>"],
			[["exit", { type: "content" }, {}], "[青空]<あおぞら>>"],
		],
	},
	{
		input: "[青空] <<あおぞら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青空] <<あおぞら>>"],
			[["enter", { type: "paragraph" }, {}], "[青空] <<あおぞら>>"],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], "青空] <<あおぞら>>"],
			[["exit", { type: "data" }, {}], "青空] <<あおぞら>>"],
			[["exit", { type: "paragraph" }, {}], "[青空] <<あおぞら>>"],
			[["exit", { type: "content" }, {}], "[青空] <<あおぞら>>"],
		],
	},
	{
		input: "[青空]<<あお>ぞら>>",
		expected: [
			[["enter", { type: "content" }, {}], "[青空]<<あお>ぞら>>"],
			[["enter", { type: "paragraph" }, {}], "[青空]<<あお>ぞら>>"],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], "青空]<<あお>ぞら>>"],
			[["exit", { type: "data" }, {}], "青空]<<あお>ぞら>>"],
			[["exit", { type: "paragraph" }, {}], "[青空]<<あお>ぞら>>"],
			[["exit", { type: "content" }, {}], "[青空]<<あお>ぞら>>"],
		],
	},
	...[
		"[]<<>>",
		"[]<<あお>>",
		"[青|]<<あお|>>",
		"[|空]<<|そら>>",
		"[青||空]<<あお||そら>>",
		"[|]<<|>>",
		"[青|空]<<あおぞら>>",
		"[青空]<<あお|ぞら>>",
		"[青|空]<<>>",
		"[青空]<<|>>",
		"[青天|の|霹靂]<<せいてん|>>",
		"[青|空]<<あお||>>",
		"[青|空]<<||そら>>",
	].map((input) => ({
		input,
		expected: [
			[["enter", { type: "content" }, {}], input],
			[["enter", { type: "paragraph" }, {}], input],
			[["enter", { type: "data" }, {}], "["],
			[["exit", { type: "data" }, {}], "["],
			[["enter", { type: "data" }, {}], input.slice(1)],
			[["exit", { type: "data" }, {}], input.slice(1)],
			[["exit", { type: "paragraph" }, {}], input],
			[["exit", { type: "content" }, {}], input],
		] satisfies [["enter" | "exit", Partial<Token>, Partial<TokenizeContext>], string][],
	})),
])("トークン化 ┊︎ $input", ({ input, expected }) => {
	const events = postprocess(
		parse({ extensions: [sapphireSyntax()] })
			.document()
			.write(preprocess()(input, undefined, true)),
	);

	const serializedEvents = events.map((event) => {
		const [, token, context] = event;
		return [event, context.sliceSerialize(token)] satisfies [Event, string];
	});

	expect(serializedEvents).toMatchObject(expected);
});
